[path]
root=D:\NextCloud\SolarRadiation
input=${root}\Full_Dataset
output_root=${root}\Output\${model:model_name}
evaluation=${root}\Output
checkpoints=${root}\Checkpoints\${model:model_name}
cache=${root}\CachedData
figures_output=${output_root}\Figures\${model:model_name}
log=log
reduced_dataset=True

[model]
model_name = cnn
# Possible model names: knn,krr,mlp,1dcnn,4dnn,ann,cnn,rbfnn,ndcnn,idw,regular_interp,rbf_interp
models_to_run = cnn,1dcnn,knn,4dnn
number_of_trials=16
batch_size=16
early_stopping_after=40
epochs=100

[visualization]
plot_after_training=False
fontsize=14
dpi = 200
reconstruction_method=nearest
reconstruction_n_neighbors=5